substitutions:
  device_friendly_name: "Haier YR-M09"
  device_id: "haier_yr_m09"
  device_name: "haier-yr-m09"
  ir_send_pin: 14
  ir_recv_pin: 5
  status_led_pin: 15

esphome:
  name: $device_name
  friendly_name: $device_friendly_name

esp8266:
  board: esp_wroom_02

# DEBUG 等级将输出接收数据
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret haier_yr_m09_key
  actions:
    - action: send_raw_ir
      variables:
        raw_data: 'int[]'
      then:
        - remote_transmitter.transmit_raw:
              code: !lambda 'return raw_data;'
              carrier_frequency: 38kHz
    - action: send_nec_ir
      variables:
        address: int
        command: int
      then:
        - remote_transmitter.transmit_nec:
            address: !lambda 'return address;'
            command: !lambda 'return command;'

ota:
  - platform: esphome
    password:  !secret haier_yr_m09_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Haier YR-M09 Hotspot"
    password: !secret hotspot_password

captive_portal:

external_components:
  - source:
      type: local
      path: external_components
    components: [ haier_ir_acyrm09  ]

status_led:
  pin: $status_led_pin

remote_receiver:
  - id: ir_receiver
    pin:
      number: $ir_recv_pin
      inverted: True
    # dump: raw

remote_transmitter:
  - id: ir_transmitter
    pin: $ir_send_pin
    carrier_duty_percent: 50%

# 外部温度计
sensor:
  - platform: homeassistant
    id: ${device_id}_temperature
    entity_id: !secret haier_yr_m09_temperature

switch:
  - platform: haier_ir_acyrm09
    haier_acyrm09_id: $device_id
    health:
      name: "Health"
      id: ${device_id}_health
    heating:
      name: "Heating"
      id: ${device_id}_heating

climate:
  - platform: haier_ir_acyrm09
    id: $device_id
    name: $device_friendly_name
    sensor: ${device_id}_temperature
    receiver_id: ir_receiver
    transmitter_id: ir_transmitter
