substitutions:
  device_friendly_name: "Haier YR-H63"
  device_id: "haier_yr_h63"
  device_name: "haier-yr-h63"
  reset_pin: 4
  status_led_pin: 15

packages:
  wifi: !include
    file: common/wifi.yaml
    vars:
      ssid: ${device_friendly_name}
  haier_yr_h63: !include
    file: common/haier_yr_h63.yaml
    vars:
      ir_recv_pin: 3
      ir_send_pin: 1
      climate_id: ${device_id}
      climate_name: ${device_friendly_name}
      temperature_sensor: ${device_id}_temperature

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

esp8266:
  board: esp_wroom_02

# DEBUG 等级将输出接收数据
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret haier_yr_h63_key

ota:
  - platform: esphome
    password:  !secret haier_yr_h63_password

status_led:
  pin: ${status_led_pin}

# 外部温度计
sensor:
  - platform: homeassistant
    id: ${device_id}_temperature
    entity_id: !secret haier_yr_h63_temperature
