substitutions:
  device_friendly_name: "Haier YR-M09"
  device_id: "haier_yr_m09"
  device_name: "haier-yr-m09"
  reset_pin: 4
  status_led_pin: 15

packages:
  wifi: !include
    file: common/wifi.yaml
    vars:
      ssid: ${device_friendly_name}
  ir_remote: !include
    file: common/ir_remote.yaml
    vars:
      ir_recv_pin: 5
      ir_send_pin: 14
  haier_yr_m09: !include
    file: common/haier_yr_m09.yaml
    vars:
      ir_receiver: ir_receiver_5
      ir_transmitter: ir_transmitter_14
      climate_id: ${device_id}
      climate_name: ${device_friendly_name}
      temperature_sensor: ${device_id}_temperature

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

esp8266:
  board: esp_wroom_02

# DEBUG 等级将输出接收数据
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret haier_yr_m09_key

ota:
  - platform: esphome
    password:  !secret haier_yr_m09_password

status_led:
  pin: $status_led_pin

# 外部温度计
sensor:
  - platform: homeassistant
    id: ${device_id}_temperature
    entity_id: !secret haier_yr_m09_temperature
