packages:
  wifi: !include
    file: common/wifi.yaml
    vars:
      ssid: PC Switch

esphome:
  name: pc-switch
  friendly_name: PC Switch

esp8266:
  board: esp12e

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret pc_switch_key

ota:
  - platform: esphome
    password: !secret pc_switch_password

wifi:
  # 省电模式
  power_save_mode: light

captive_portal:

output:
  # 电源
  - platform: gpio
    id: output_power
    pin: 4
  # 重启
  - platform: gpio
    id: output_reboot
    pin: 5
  # LED
  - platform: gpio
    id: output_led
    pin:
      number: 2
      inverted: true

binary_sensor:
  # 开机状态
  - platform: gpio
    id: binary_sensor_status
    pin: 12
    name: status
    icon: "mdi:power"
    device_class: power
    internal: true

switch:
  # 开关机
  - platform: template
    id: switch_power
    name: switch
    icon: "mdi:power"
    lambda: 'return id(binary_sensor_status).state;'
    turn_on_action:
      - button.press: button_power
    turn_off_action:
      - button.press: button_power
    restore_mode: DISABLED
  # LED
  - platform: output
    id: switch_led
    name: LED
    icon: "mdi:led-on"
    output: output_led

button:
  # 开机/关机
  - platform: output
    id: button_power
    name: power
    icon: "mdi:power"
    output: output_power
    duration: 500ms
  # 强制关机
  - platform: output
    id: button_shutdown
    name: shutdown
    icon: "mdi:power"
    output: output_power
    duration: 5000ms
  # 重启
  - platform: output
    id: button_reboot
    name: reboot
    icon: "mdi:power"
    output: output_reboot
    duration: 500ms
