esphome:
  includes:
    - common/helpers.h

external_components:
  - source:
      type: local
      path: external_components
    components: [ sw_remote_receiver ]

sw_remote_receiver:
  - id: rf_receiver_${rf_recv_pin}
    pin:
      number: ${rf_recv_pin}
      mode: INPUT_PULLDOWN
    tolerance: 50%
    # dump: all
    on_raw:
      - lambda: |-
          if (!id(rf_dump_${rf_recv_pin}).state) return;
          const char* TAG = "RF dump ${rf_recv_pin}";
          on_raw_dump(TAG, x);
    on_rc_switch:
      - lambda: |-
          std::string result= format_rc_switch_data(x);
          id(rf_code_${rf_recv_pin}).publish_state(result);
      - delay: 200ms
      - lambda: 'id(rf_code_${rf_recv_pin}).publish_state("reset");'

api:
  actions:
    - action: send_raw_rf_${rf_send_pin}
      variables:
        raw_data: 'int[]'
        times: int
      then:
        - lambda: |-
            id(rf_transmitter_ab).set_pin((gpio_num_t)${rf_send_pin});
        - remote_transmitter.transmit_raw:
            transmitter_id: rf_transmitter_ab
            code: !lambda 'std::vector<long int> std_vec(raw_data.begin(), raw_data.end()); return std_vec;'
            repeat:
              times: !lambda 'return times;'
              wait_time: 0s
    - action: send_rc_switch_rf_${rf_send_pin}
      variables:
        code: string
        protocol: int
        times: int
      then:
        - lambda: |-
            id(rf_transmitter_ab).set_pin((gpio_num_t)${rf_send_pin});
        - remote_transmitter.transmit_rc_switch_raw:
            transmitter_id: rf_transmitter_ab
            code: !lambda 'return code;'
            protocol: !lambda 'return remote_base::RC_SWITCH_PROTOCOLS[protocol];'
            repeat:
              times: !lambda 'return times;'
              wait_time: 0s
    - action: send_ev1527_rf_${rf_send_pin}
      variables:
        code: string
        pulse_length: int
        times: int
      then:
        - lambda: |-
            id(rf_transmitter_ab).set_pin((gpio_num_t)${rf_send_pin});
        - remote_transmitter.transmit_rc_switch_raw:
            transmitter_id: rf_transmitter_ab
            code: !lambda 'return code;'
            protocol: !lambda 'return remote_base::RCSwitchBase(pulse_length, pulse_length * 31, pulse_length, pulse_length * 3, pulse_length * 3, pulse_length, false);'
            repeat:
              times: !lambda 'return times;'
              wait_time: 0s

text_sensor:
  - platform: template
    id: rf_code_${rf_recv_pin}
    name: RF code ${rf_recv_pin}
    icon: "mdi:code-json"

switch:
  - platform: template
    id: rf_dump_${rf_recv_pin}
    name: RF dump ${rf_recv_pin}
    icon: "mdi:record-rec"
    optimistic: true
