esphome:
  includes:
    - common/helpers.h

api:
  actions:
    - action: send_raw_rf_${rf_send_pin}
      variables:
        raw_data: 'int[]'
      then:
        - remote_transmitter.transmit_raw:
            transmitter_id: rf_transmitter_${rf_send_pin}
            code: !lambda 'std::vector<long int> std_vec(raw_data.begin(), raw_data.end()); return std_vec;'
            repeat:
              times: 10
              wait_time: 0s
    - action: send_rc_switch_rf_${rf_send_pin}
      variables:
        code: string
        protocol: int
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            transmitter_id: rf_transmitter_${rf_send_pin}
            code: !lambda 'return code;'
            protocol: !lambda 'return remote_base::RC_SWITCH_PROTOCOLS[protocol];'
            repeat:
              times: 10
              wait_time: 0s

remote_receiver:
  - id: rf_receiver_${rf_recv_pin}
    # rmt_symbols: 48
    # filter_symbols: 4
    pin: ${rf_recv_pin}
    tolerance: 50%
    # dump: all
    on_raw:
      - lambda: |-
          if (!id(rf_dump_${rf_recv_pin}).state) return;
          const char* TAG = "RF dump ${rf_recv_pin}";
          on_raw_dump(TAG, x);
    on_rc_switch:
      - lambda: |-
          std::string result = format_rc_switch_data(x);
          id(rf_code_${rf_recv_pin}).publish_state(result);

remote_transmitter:
  - id: rf_transmitter_${rf_send_pin}
    pin: ${rf_send_pin}
    carrier_duty_percent: 100%

text_sensor:
  - platform: template
    id: rf_code_${rf_recv_pin}
    name: RF code ${rf_recv_pin}
    icon: "mdi:code-json"

switch:
  - platform: template
    id: rf_dump_${rf_recv_pin}
    name: RF dump ${rf_recv_pin}
    icon: "mdi:record-rec"
    optimistic: true
